name: approvals_hte
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  flutter_secure_storage: ^9.2.4
  go_router: ^16.3.0
  logger: ^2.6.2
  convex_bottom_bar: ^3.2.0
  geolocator: ^12.0.0
  mobile_scanner: ^6.0.0
  flutter_pdfview: ^1.4.3
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
